### ISSUE TITLE
inf-ruby-console-auto doesn't work on rails 6

### ISSUE THREAD

**Issue by mjhoy** [mjhoy/dotfiles#26]
```
Traceback (most recent call last):
	9: from bin/rails:4:in `<main>'
	8: from bin/rails:4:in `require'
	7: from /Users/mikeyhoy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	6: from /Users/mikeyhoy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0.rc1/lib/rails/command.rb:46:in `invoke'
	5: from /Users/mikeyhoy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-6.0.0.rc1/lib/rails/command/base.rb:65:in `perform'
	4: from /Users/mikeyhoy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	3: from /Users/mikeyhoy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	2: from /Users/mikeyhoy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:20:in `run'
	1: from /Users/mikeyhoy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:34:in `rescue in run'
/Users/mikeyhoy/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:506:in `handle_argument_error': ERROR: "rails console" was called with arguments ["development"] (Thor::InvocationError)
Usage: "rails console [options]"

```

**Comment by mjhoy** [comment]
fixed in https://github.com/mjhoy/dotfiles/commit/55645b69ea01b6980e0f3b12fa60a081de1bb9c4
